### ISSUE TITLE
add datatype to JSON context

### ISSUE THREAD

**Issue by kurzum** [NLP2RDF/NIF-lib#14]
e.g. xsd:nonNegativeInteger

**Comment by sandroacoelho** [comment]
Hi @kurzum ,
It's done!

```
 ...     
"beginIndex": {
            "@id": "http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#beginIndex",
            "@type": "http://www.w3.org/2001/XMLSchema#nonNegativeInteger"
 }
...
```

You can see the result through the [jsonld-context.io](http://www.jsonld-context.io). Our microservice to generate contexts from whatever ontology
