### ISSUE TITLE
error in readme 3. part

### ISSUE THREAD

**Issue by v-mostafapour** [NLP2RDF/NIF-lib#16]
in readme example  3. part
I wonder whether "beans.add(contextBuilder);" must change to beans.add(beanContext);?

**Comment by sandroacoelho** [comment]
HI @v-mostafapour ,

Thank you for debugging it. I will fix it ASAP

Best,

**Comment by sandroacoelho** [comment]
Hi @v-mostafapour ,

Fixed. I have also added a new example [here](https://github.com/NLP2RDF/NIF-lib/wiki)

Best,

**Comment by v-mostafapour** [comment]
Hi Sandro,

Thank you.

Best Regards,
